### ISSUE TITLE
Consider requirements.txt file

### ISSUE THREAD

**Issue by malmaud** [mattgolub/fixed-point-finder#3]
Since all the dependencies seem to be installable via `pip`, you can create a [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) file that lists them to make it easy for others to install the dependencies.

**Comment by mattgolub** [comment]
@malmaud  Thanks for the great suggestion. I've created requirements.txt files and updated the installation instructions in the README.
