### ISSUE TITLE
Error when running example code

### ISSUE THREAD

**Issue by cversteeg** [mattgolub/fixed-point-finder#5]
Thanks for releasing this; looking forward to doing some testing. I was trying to run the example and got an attribute error.

  File "/home/chris/Documents/git/fixed-point-finder/src/recurrent-whisperer/RecurrentWhisperer.py", line 653, in _train_epoch
    batch_summary = self._train_batch(batch_data)

  File "FlipFlop.py", line 207, in _train_batch
    self.merged_opt_summary]

AttributeError: 'FlipFlop' object has no attribute 'merged_opt_summary'

I fixed it by changing merged_opt_summaries in RecurrentWhisperer to merged_opt_summary and got it working.

Thanks again!
Chris

**Comment by mattgolub** [comment]
Thanks for pointing this out. I'm glad you were able to find the quick fix. The installation was pointing to an out-of-date version of RecurrentWhisperer, but should be fixed now.

Let me know if you do something cool with this!
